### PR TITLE
Fixes #2

### LINKED ISSUE #2: Deprecated API
Hi, just FYI seems like this plugin is hitting a deprecated API and not working as of (Pre-release) 2.2.4. More info: https://discourse.joplinapp.org/t/important-plugins-that-use-deprecated-apis-will-no-longer-work/19278

```
18:59:53: joplin.plugins: Uncaught exception in plugin "joplin.plugin.ambrt.convertToNewNote": Error: "joplin.plugin.ambrt.convertToNewNote": No longer supported: joplin.settings.registerSetting() is deprecated in favour of joplin.settings.registerSettings() (deprecated since version 1.8)
    at Plugin.deprecationNotice (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/plugins/Plugin.js:117)
    at JoplinSettings.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/plugins/api/JoplinSettings.js:85)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/plugins/api/JoplinSettings.js:8
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/plugins/api/JoplinSettings.js:4)
    at JoplinSettings.registerSetting (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/plugins/api/JoplinSettings.js:84)
    at Object.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/plugins/utils/executeSandboxCall.js:50)
    at Generator.next (<anonymous>)
    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/plugins/utils/executeSandboxCall.js:8
```

### PR DESCRIPTION
**Pull request by Petemir**
`registerSetting` API method has been deprecated. This pull request updates the call to `registerSettings`. Fixes #2 .

### CODE REVIEW

**Comment by tessus** [comment]
This is not the best fix, since you call `registerSettings` the same number of times as `registerSetting`. The whole reason for the new api call was to minimize the number of slow calls and bundle it into a single call.

**Comment by Petemir** [comment]
> This is not the best fix, since you call `registerSettings` the same number of times as `registerSetting`. The whole reason for the new api call was to minimize the number of slow calls and bundle it into a single call.

You are right, I just focused on fixing the error and didn't really think (nor knew) about the reasoning behind the API change :). Now it should be good to go.

**Comment by tessus** [comment]
Great, let's hope the repo owner merges this soon.

**Comment by ambrt** [comment]
Published to npm, should be available soon.

**Pull request merged**
